global:
  scrape_interval: 15s
  evaluation_interval: 15s

remote_write:
  - url: https://prometheus-prod-37-prod-ap-southeast-1.grafana.net/api/prom/push
    basic_auth:
      username: {GRAFANA_USER}
      password: {GRAFANA_TOKEN}

scrape_configs:
  - job_name: kong
    static_configs:
      - targets:
          - kong:8001